name: 'Run Copyright and license check with Patch File'
description: 'A GitHub Action to run a Copyright and license checker with a patch file'
inputs:
  patch_file:
    description: 'The patch file to apply'
    required: true
    default: 'patch_file.patch'
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run checker
      run: python main.py ${{ inputs.patch_file }}
branding:
  icon: 'python'
  color: 'blue'
