name: 'Run Copyright and license check with Patch File'
description: 'A GitHub Action to run a Copyright and license checker with a patch file'
inputs:
  patch_file:
    description: 'The patch file to apply'
    required: true
    default: 'patch_file.patch'
  repo_name:
    description: 'The name of the github repository'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2
      with:
        python-version: 3.12

    - name: Install pip-tools
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
      shell: bash

    - name: Install dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Run checker
      env:
        ACTION_PATH: ${{ github.action_path }}
        PATCH_FILE: ${{ inputs.patch_file }}
        REPO_NAME: ${{ inputs.repo_name }}
      run: python "$ACTION_PATH/main.py" "$PATCH_FILE" "$REPO_NAME"
      shell: bash

branding:
  icon: 'python'
  color: 'blue'
