name: 'Run Copyright and license check with Patch File'
description: 'A GitHub Action to run a Copyright and license checker with a patch file'
inputs:
  patch_file:
    description: 'The patch file to apply'
    required: true
    default: 'patch_file.patch'
  repo_name:
    description: 'The name of the github repository'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install pip-tools
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
      shell: bash

    - name: Install dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Run checker
      run: python "${{ github.action_path }}/main.py" "${{ inputs.patch_file }}" "${{ inputs.repo_name }}"
      shell: bash

branding:
  icon: 'python'
  color: 'blue'
